version: '3.1'

services:
  db:
      image: postgres:15
      restart: always
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: user
        POSTGRES_DB: ride_together
        PGDATA: /var/lib/postgresql/data/
      ports:
        - 5432:5432
      volumes:
        - db:/var/lib/postgresql/data/
